name: CI
on:
  schedule:
    - cron:  '0 1 27 12 *'
  push:
    paths: "README.md"
    tags-ignore: "auto-*"
    branches: [ master ]
  pull_request:
    tags-ignore: "auto-*"
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Age
        run: |
          chmod +x set_age.sh
          ./set_age.sh
          git config --global user.name 'OLeonardoRodrigues'
          git config --global user.email 'oleonardorodrigues@users.noreply.github.com'
          git commit -am "Age Updated"
          git tag auto-$(date +%s)
          git push --tags -u origin master
