name: CI
on:
  schedule:
    - cron:  '0 1 27 12 *'
  push:
    tags-ignore: "auto-*"
    branches: [ master ]
  pull_request:
    tags-ignore: "auto-*"
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: chmod +x set_age.sh
      - name: Run a multi-line script
        run: ./set_age.sh
      - name: UUID Action
        # You may pin to the exact commit or the version.
        # uses: filipstefansson/uuid-action@ce29ebbb0981ac2448c2e406e848bfaa30ddf04c
        uses: filipstefansson/uuid-action@v1.1
        with:
          name: tagid
      - name: Commit report
        run: |
          git config --global user.name 'OliveiraLeonardo17'
          git config --global user.email 'oliveiraleonardo17@users.noreply.github.com'
          git commit -am "Automated report"
          git tag "auto-${{ steps.generate-uuid.outputs.uuid }}"
          git push --tags
      
