name: CI
on:
  schedule:
    - cron:  '0 1 27 12 *'
  push:
    tags-ignore: "auto-*"
    branches: [ master ]
  pull_request:
    tags-ignore: "auto-*"
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Commit report
        run: |
          chmod +x set_age.sh
          ./set_age.sh
          git config --global user.name 'OliveiraLeonardo17'
          git config --global user.email 'oliveiraleonardo17@users.noreply.github.com'
          git commit -am "Automated report"
          git tag auto-$(date +%s)
          git push --tags -u origin master
